var express = require("express");
var router = express.Router();
const torneoController = require('../controllers/torneos.controller');
const passport = require("passport");
router.get('/',torneoController.findAll);
router.post('/',torneoController.create);
router.get('/:id/validar',passport.authenticate('jwt',{session:false}),torneoController.findParticipante);
router.put('/:id',torneoController.updateParticipante);
router.get('/:id',torneoController.findId);
router.delete('/:id',torneoController.deleteID);
module.exports = router;